config/routes.rb
Rails.application.routes.draw do

  get 'users/show'

  devise_for :users
  resources :users, only: [:show]

  resources :topics do
    resources :bookmarks, except: [:index]
  end

  resources :bookmarks, except: [:index] do
    resources :likes, only: [:create, :destroy]
  end

  post :incoming, to: 'incoming#create'
  
  get 'about' => 'welcome#about'

  root to: 'welcome#index'
end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base

  belongs_to :topic
  belongs_to :user
  has_many :likes, dependent: :destroy
  
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :bookmark
  belongs_to :user
end

app/models/topic.rb
class Topic < ActiveRecord::Base

  belongs_to :user
  has_many :bookmarks

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :topics
  has_many :bookmarks
  has_many :likes, dependent: :destroy

  def liked(bookmark)
    likes.where(bookmark_id: bookmark.id).first
  end

  def get_ordered_bookmarks
    current_topic = nil
    bookmarks_by_topic = []
    # loop through users bookmarks and if current_topic changes, then create new hash
    self.bookmarks.each do |bookmark|
      if current_topic != bookmark.topic
        current_topic = bookmark.topic
        topic_hash = {topic_name: current_topic.title, bookmarks: []}
      end

    end
  end

  # [
  # {topic_name: 'test topic name', bookmarks: [bookmarks]},
  # {topic_name: 'test topic name 2', bookmarks: [bookmarks]}
  # ]
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    topics_path
  end

  rescue_from Pundit::NotAuthorizedError do |exception|
    redirect_to root_url, alert: exception.message
  end

 
protected
 
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end

end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :authenticate_user!

  def show
    @bookmarks = Bookmark.all
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @bookmark = @topic.bookmarks.new
    authorize @bookmark
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @bookmark = @topic.bookmarks.build(params.require(:bookmark).permit(:url))
    @bookmark.user_id = current_user.id
    if @bookmark.save
      flash[:notice] = "Bookmark was created"
      redirect_to topics_path
    else
      flash[:error] = "Error creating bookmark"
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:topic_id])
    @bookmark = @topic.bookmarks.find(params[:id])
    authorize @bookmark

    if @bookmark.update_attributes(params.require(:bookmark).permit(:url))
      redirect_to topics_path, notice: "Bookmark was updated"
    else
      flash[:error] = "Error updating bookmark"
      render :edit
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    authorize @bookmark

    if @bookmark.destroy
      flash[:notice] = "Bookmark was deleted successfully."
      redirect_to topics_path
    else
      flash[:error] = "There was an error deleting the bookmark."
      render :show
    end
  end

end

app/controllers/incoming_controller.rb
class IncomingController < ApplicationController
  # http://stackoverflow.com/questions/1177863/how-do-i-ignore-the-authenticity-token-for-specific-actions-in-rails
  skip_before_action :verify_authenticity_token, only: [:create]

  def index
  end

  def create

    puts ">>>>>>>>>> #{params.inspect}"

    user = User.find_by(email: params[:sender])
    subject = params[:subject]
    content = params[:'body-plain']

    topic = user.topics.find_or_create_by(title: subject)

    bookmark = user.bookmarks.build(topic: topic, url: content)

    if bookmark.save
      head 200
    else
      head :no_content
    end

    # if @user
      
    # else
    #   @user = User.create(email: params[:sender])
    # end
    # puts @user
    # @topic = Topic.find_by(email: params[:subject])
    # @url = params["body-plain"]

    # if @user_id == nil?
    # user.create
    # end

    # if @topic_id == nil?
    # topic.create
    # end

    # You put the message-splitting and business
    # magic here.
    # Find the user by using params[:sender]
    # Find the topic by using params[:subject]
    # Assign the url to a variable after retreiving it from params["body-plain"]
    # Check if user is nil, if so, create and save a new user
    # Check if the topic is nil, if so, create and save a new topic
    # Now that we're sure we have a valid user and topic, build and save a new bookmark
    # Assuming all went well. 

    head 200
  end
  
end
# RestClient.post 'http://localhost:3000/incoming', {params: {sender: 'bdsimmons1@gmail.com'}}

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @bookmark = Bookmark.find(params[:bookmark_id])
    like = current_user.likes.build(bookmark: @bookmark)
    @like = like
    authorize like
 
    if like.save
      flash[:notice] = "Like status added"
    else
      flash[:error] = "Error updating Like status"
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:bookmark_id]) 
    like = current_user.likes.find(params[:id])  
    authorize like

    if like.destroy
      flash[:notice] = "Like status removed"
    else
      flash[:error] = "Error removing Like status"
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!

  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.find(params[:id])
    @bookmarks = @topic.bookmarks
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(params.require(:topic).permit(:title))
    if @topic.save
      flash[:notice] = "Topic was saved."
      redirect_to topics_path
    else
      flash[:error] = "There was an error saving the topic. Please try again."
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])
    if @topic.update_attributes(params.require(:topic).permit(:title))
      flash[:notice] = "Topic was updated."
      redirect_to topics_path
    else
      flash[:error] = "There was an error saving the topic. Please try again."
      render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    if @topic.destroy
      flash[:notice] = "Topic was deleted successfully."
      redirect_to topics_path
    else
      flash[:error] = "There was an error deleting the topic."
      render :show
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user_bookmarks = current_user.bookmarks.order(:topic_id)
    @topics = @user_bookmarks.collect(&:topic)
    @user_liked_bookmarks = current_user.likes.collect(&:bookmark)
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/incoming_helper.rb
module IncomingHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bookmarks/edit.html.erb
<h1> Edit Bookmark URL </h1>
<br>
<%= form_for [@topic, @bookmark] do |f| %>
  <div class="form-group">
    <%= f.text_field :url, class: 'form-control', placeholder: "Copy Web Address Here" %>
    </div>
    <%= f.submit "Save", class: 'btn btn-success' %>
  <% end %>

app/views/bookmarks/new.html.erb
<h1> Create New Bookmark URL </h1>
<br>
<%= form_for [@topic, @bookmark] do |f| %>
  <div class="form-group">
    <%= f.text_field :url, class: 'form-control', placeholder: "Copy Web Address Here" %>
    </div>
    <%= f.submit "Save", class: 'btn btn-success' %>
  <% end %>

app/views/bookmarks/show.html.erb
<h1>Bookmarks#show</h1>
<p>Find me in app/views/bookmarks/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocmarks</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="container">
      <ul>
      <ul class="nav nav-tabs">
        <% if current_user %>
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "All Bookmarks", topics_path %></li>
          <li><%= link_to "My Bookmarks", users_show_path %></li>
        <% else %>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About", about_path %></li>
      <% end %>

        <div class="pull-right user-info">
           <% if current_user %>
             <%= link_to current_user.email, edit_user_registration_path %> |
             <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
           <% else %>
             <%= link_to "Sign In", new_user_session_path %> or 
             <%= link_to "Sign Up", new_user_registration_path %>
           <% end %>
         </div>
    </ul>
     
    <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
    <% elsif flash[:error] %>
        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:error] %>
        </div>
    <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
    <% end %> 

<%= yield %>

    </div>

</body>
</html>

app/views/likes/_like.html.erb
<% if like = current_user.liked(bookmark) %>
  <%= link_to [bookmark, like], method: :delete, remote: true do %>
    <i id="bookmark-<%= bookmark.id %>" class="glyphicon glyphicon-star"> </i>
  <% end %>
<% else %>
  <%= link_to [bookmark, Like.new], method: :post, remote: true do %>
    <i id="bookmark-<%= bookmark.id %>" class="glyphicon glyphicon-star-empty"> </i>
  <% end %>
<% end %>

app/views/likes/create.js.erb
var $el = $('#bookmark-<%= @bookmark.id %>');
$el.removeClass('glyphicon-star-empty');
$el.addClass('glyphicon-star');
var $link = $el.parent('a');
$link.data('method', 'delete');
$link.attr('href', '<%= bookmark_like_path(@bookmark, @like) %>');

app/views/likes/destroy.js.erb
var $el = $('#bookmark-<%= @bookmark.id %>');
$el.removeClass('glyphicon-star');
$el.addClass('glyphicon-star-empty');
$el.parent('a').data('method', 'post');
$el.parent('a').attr('href', '<%= bookmark_likes_path(@bookmark, Like.new) %>');

app/views/topics/edit.html.erb
<h1>Edit Topic</h1>
<br>
<%= form_for @topic do |f| %>
    <div class="form-group">
      <%= f.text_field :title, class: 'form-control', placeholder: @topic.title %>
    </div>
      <%= f.submit "Save", class: 'btn btn-success' %>
<% end %>

app/views/topics/index.html.erb
<h3>All Bookmarks</h3>
<h6><%= link_to "New Topic", new_topic_path %></h6>
<h6>Click on "Topic Title" to create New Bookmark</h6>
<br>
  <div>
    <% @topics.each do |topic| %> 
      <table class="table"> 
          <h4><%= link_to topic.title, topic %></h4>
        <thead>
            <tr>
            <th>Liked</th>
            <th>Bookmark URL</th>
            <th>Added By</th>
            </tr>
        </thead>
        <tbody>
          <% topic.bookmarks.each do |bookmark| %>
            <tr> 
            <td><%= render partial: 'likes/like', locals: { bookmark: bookmark } %></td>
            <td><%= link_to bookmark.url, bookmark.url, target: '_blank' %></td>
            <td><%= bookmark.user.email %></td>
            </tr> 
          <% end %>
        </tbody>
        <% end %>
      </table>
    </div>
<br>

app/views/topics/new.html.erb
<h1> Create New Topic </h1>
<br>

<%= form_for @topic do |f| %>
   <div class="form-group">
   <%= f.text_field :title, class: 'form-control', placeholder: "New Topic Title" %>
   </div>
   <%= f.submit "Save", class: 'btn btn-success' %>
  <% end %>

app/views/topics/show.html.erb
<h1><%= @topic.title %></h1>
<%= link_to "Edit Topic", edit_topic_path(@topic) %> |
<%= link_to "Delete Topic", @topic, method: :delete, data: { confirm: 'Are you sure you want to delete topic?' } %> |
<%= link_to "New Bookmark", new_topic_bookmark_path(@topic) %> 
<br>
<br>
<br>
<div>
  <table class="table">
    <thead>
            <tr>
            <th>Edit</th>
            <th>Delete</th>
            <th>Bookmark URL</th>
            <th>Added By</th>
            </tr>
        </thead>
<% @bookmarks.each do |bookmark| %>
      <tbody>
        <tr>
          <td><%= link_to "Edit", edit_topic_bookmark_path(@topic, bookmark) %></td>
          <td><%= link_to "Delete", topic_bookmark_path(@topic, bookmark), method: :delete, data: {confirm: 'Are you sure you want to delete bookmark?'} %></td>
          <td><%=link_to bookmark.url, bookmark.url, target: '_blank' %></td>
          <td><%= bookmark.user.email %></td>
        </tr> 
      </tbody>
  <% end %>
</div>

app/views/users/show.html.erb
<div>
    <table class="table"> 
        <h3>My Liked Bookmarks</h3>
      <thead>
          <tr>
          <th>Liked</th>
          <th>Topic</th>
          <th>Bookmark URL</th>
          <th>Added By</th>
          </tr>
      </thead>
      <tbody>
        <% @user_liked_bookmarks.each do |bookmark| %>
          <tr>
          <td><%= render partial: 'likes/like', locals: { bookmark: bookmark } %></td>
          <td><%= bookmark.topic.title %></td>
          <td><%= link_to bookmark.url, bookmark.url, target: '_blank' %></td>           
          <td><%= bookmark.user.email %></td>
          </tr> 
        <% end %>
      </tbody>
    </table>
</div>
<br>
<div>
    <table class="table"> 
        <h3>My Bookmarks</h3>
      <thead>
          <tr>
          <th>Liked</th>
          <th>Topic</th>
          <th>Bookmark URL</th>
          <th>Added By</th>
          </tr>
      </thead>
      <tbody>
        <% @user_bookmarks.each do |bookmark| %>
          <tr>
          <td><%= render partial: 'likes/like', locals: { bookmark: bookmark } %></td>
          <td><%= bookmark.topic.title %></td>
          <td><%= link_to bookmark.url, bookmark.url, target: '_blank' %></td>           
          <td><%= bookmark.user.email %></td>
          </tr> 
        <% end %>
      </tbody>
    </table>
</div>
<br>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<br/>
<div class="jumbotron">
  <h1>BlocMarks</h1>
  
  <p>
      <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary' %> or 
      <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %>
  </p>
</div>